name: com.maximde.customscores.spigot.CustomScoreNumbers
description: = 'Customize the scoreboard sidebar numbers'
version: '${version}'
main: com.maximde.customscorenumbers.bukkit.com.maximde.customscores.spigot.CustomScoreNumbers
api-version: '1.20'
author: MaximDe
website: "https://www.spigotmc.org/resources/115955/"
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot

commands:
  customscores: