name: CustomScoreNumbers
version: '${version}'
main: com.maximde.customscorenumbers.CustomScoreNumbers
api-version: '1.20'
author: MaximDe
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot

commands:
  customscores: